baseURL = "https://yingsa.site/"
languageCode = "zh-cn"
title = "我的博客"
theme = "PaperMod"

[params]
  author = "bonobo10086"
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"
  mainSections = ["posts"]


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2

